#!/usr/bin/env bash

case "$TECH" in
  go)
    export PATH=$PATH:/usr/local/go/bin
    ;;
esac

git clone --single-branch --branch "$BRANCH" "$REPOURL"

snyk auth "$SNYK_API_KEY"
snyk test --severity-threshold=medium --all-projects --org="$SNYK_ORG_ID" --json-file-output=/app/sca-results.json